name: to_read_list
description: to read list

isar_version: &isar_version 3.0.5

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_sharing_intent: 1.0.5

  isar: *isar_version
  isar_flutter_libs: *isar_version

  url_launcher: 6.1.10

  any_link_preview: 3.0.0

  hooks_riverpod: ^2.3.6

  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  isar_generator: *isar_version
  build_runner: 2.3.3

flutter:
  uses-material-design: true
  generate: true